#' Generic Summary Method for GEESAR
#' 
#' Defines a generic method for summarizing GEESAR model objects.
#' 
#' @param object An object to summarize.
#' @param ... Additional arguments passed to the method.
#' 
#' @export
summary <- function(object, ...) {
  UseMethod("summary")
}



#' Summary Method for GEESAR Objects
#'
#' Provides a summary of a GEESAR model object.
#'
#' @param object An object of class `"GEESAR"`, generated by the `GEESAR()` function.
#' @param ... Additional arguments (currently unused).
#'
#' @return A list of class `"summary.GEESAR"`.
#' @export
summary.GEESAR <- function(object, ...) {
  if (!inherits(object, "GEESAR")) 
    stop("The object must be of class 'GEESAR'.")
  
  beta_hat <- object$coefficients
  vcov_matrix <- object$vcovs
  std_error <- sqrt(diag(vcov_matrix))
  Z_stat <- beta_hat / std_error
  p_values <- 2 * (1 - pnorm(abs(Z_stat)))
  
  rho_hat <- object$rho
  varrho_hat <- object$varrho  
  
  coef_table <- cbind(
    Estimate = beta_hat,
    Std.Error = std_error,
    Z.value = Z_stat,
    P.value = p_values
  )
  colnames(coef_table) <- c("Estimate", "Std.Error", "z value", "P(>|z|)")
  
  summary_obj <- list(
    coefficients = coef_table,
    rho = rho_hat,
    varrho = varrho_hat,
    dispersion = object$phi,
    df.residual = object$df.residual,
    call = object$call,
    family = object$family$family,
    logLik = object$logLik,
    CIC = object$CIC,
    RJC = object$RJC
  )
  
  class(summary_obj) <- "summary.GEESAR"
  return(summary_obj)
}


#' Print Method for Summary of GEESAR Objects
#' 
#' Prints a formatted summary of a GEESAR model.
#'
#' @param x An object of class `"summary.GEESAR"`.
#' @param ... Additional arguments (currently unused).
#' @export
print.summary.GEESAR <- function(x, ...) {
  cat("\nSummary of GEESAR Model\n")
  cat("=========================================================\n")
  cat("Family:", x$family, "\n")
  cat("Call:", deparse(x$call), "\n")
  cat("---------------------------------------------------------\n")
  cat("Coefficients:\n")
  printCoefmat(x$coefficients, digits = 4, signif.stars = TRUE)
  cat("---------------------------------------------------------\n")
  cat("Estimated rho:", formatC(x$rho, digits = 4, format = "f"), "\n")
  cat("Estimated variance of rho (varrho):", formatC(x$varrho, digits = 4, format = "f"), "\n")
  cat("Estimated dispersion:", formatC(x$dispersion, digits = 4, format = "f"), "\n")
  cat("Log-likelihood:", formatC(x$logLik, digits = 4, format = "f"), "\n")
  cat("CIC:", formatC(x$CIC, digits = 4, format = "f"), "\n")
  cat("RJC:", formatC(x$RJC, digits = 4, format = "f"), "\n")
  cat("Residual degrees of freedom:", x$df.residual, "\n")
  cat("=========================================================\n")
}





