#' Summary Method for GEESAR Objects
#'
#' This function provides a summary of a GEESAR model object, which is typically 
#' a result of a generalized estimating equation (GEE) analysis using the GEESAR 
#' package. It returns a detailed summary of the model, including estimated coefficients, 
#' standard errors, z-statistics, p-values, rho (correlation parameter), 
#' variance of rho, and additional model statistics such as log-likelihood, 
#' conditional information criterion (CIC), and jackknife-covariance ratio (RJC).
#'
#' @param object An object of class `"glmgee"`, generated by the GEESAR function.
#' @param ... Additional arguments (currently unused).
#'
#' @return A list of class `"summary.GEESAR"` containing:
#'   \item{coefficients}{A matrix of the estimated coefficients, standard errors, 
#'   z-values, and p-values.}
#'   \item{rho}{Estimated value of the correlation parameter.}
#'   \item{varrho}{Estimated variance of the correlation parameter rho.}
#'   \item{dispersion}{Estimated dispersion parameter of the model.}
#'   \item{df.residual}{Residual degrees of freedom.}
#'   \item{call}{The call used to generate the GEESAR model.}
#'   \item{family}{The family of the model.}
#'   \item{logLik}{The log-likelihood of the fitted model.}
#'   \item{CIC}{The Conditional Information Criterion for model fit.}
#'   \item{RJC}{The Jackknife-Covariance Ratio of the model.}
#'
#' @examples
#' \dontrun{
#'   # Assuming you have fitted a GEESAR model
#'   out_ <- GEESAR(...)
#'   summary(out_)
#' }
#'
#' @seealso \link[GEESAR]{GEESAR} for model fitting function.
#' @export
summary.GEESAR <- function(object, ...) {
  if (!inherits(object, "gsar")) 
    stop("The object must be of class 'glmgee' generated by GEESAR.", call. = FALSE)
  
  # Extract estimated coefficients
  beta_hat <- object$coefficients
  
  # Extract variance-covariance matrix
  vcov_matrix <- object$vcovs
  
  # Compute standard errors
  std_error <- sqrt(diag(vcov_matrix))
  
  # Compute Z-statistics
  Z_stat <- beta_hat / std_error
  
  # Compute p-values
  p_values <- 2 * (1 - pnorm(abs(Z_stat)))
  
  # Extract rho and its estimated variance
  rho_hat <- object$rho
  varrho_hat <- object$varrho  # Estimated variance of rho
  
  # Create coefficient summary table
  coef_table <- cbind(
    Estimate = beta_hat,
    Std.Error = std_error,
    Z.value = Z_stat,
    P.value = p_values
  )
  colnames(coef_table) <- c("Estimate", "Std.Error", "z value", "P(>|z|)")
  # Create the summary object
  summary_obj <- list(
    coefficients = coef_table,
    rho = rho_hat,
    varrho = varrho_hat,
    dispersion = object$phi,  # Estimated dispersion parameter
    df.residual = object$df.residual,
    call = object$call,
    family = object$family$family,
    logLik = object$logLik,
    CIC = object$CIC,  # Conditional Information Criterion
    RJC = object$RJC   # Jackknife-Covariance Ratio
  )
  
  class(summary_obj) <- "summary.GEESAR"
  return(summary_obj)
}

#' Print Method for Summary of GEESAR Objects
#' 
#' Custom print method for displaying the summary of GEESAR model objects. 
#' It prints detailed results, including coefficients, rho estimates, 
#' model diagnostics, and other statistics in a formatted manner.
#'
#' @param x An object of class `"summary.GEESAR"`, typically generated 
#' by the `summary.GEESAR()` function.
#' @param ... Additional arguments (currently unused).
#'
#' @return Prints the summary information to the console.
#' @export
print.summary.GEESAR <- function(x, ...) {
  cat("\nSummary of GEESAR Model\n")
  cat("=========================================================\n")
  cat("Family:", x$family, "\n")
  cat("Call:", deparse(x$call), "\n")
  cat("---------------------------------------------------------\n")
  cat("Coefficients:\n")
  printCoefmat(x$coefficients, digits = 4, signif.stars = TRUE)
  cat("---------------------------------------------------------\n")
  cat("Estimated rho:", formatC(x$rho, digits = 4, format = "f"), "\n")
  cat("Estimated variance of rho (varrho):", formatC(x$varrho, digits = 4, format = "f"), "\n")
  cat("Estimated dispersion:", formatC(x$dispersion, digits = 4, format = "f"), "\n")
  cat("Log-likelihood:", formatC(x$logLik, digits = 4, format = "f"), "\n")
  cat("CIC:", formatC(x$CIC, digits = 4, format = "f"), "\n")
  cat("RJC:", formatC(x$RJC, digits = 4, format = "f"), "\n")
  cat("Residual degrees of freedom:", x$df.residual, "\n")
  cat("=========================================================\n")
}

